# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
